const CHAR_SPACE: char = ' ';
const CHAR_TAB: char = '\t';
const CHAR_NEWLINE: char = '\n';
const CHAR_PIPE: char = '|';
const CHAR_GT: char = '>';
const CHAR_LT: char = '<';
const CHAR_EQL: char = '=';
const CHAR_SQUOTE: char = '\'';
const CHAR_DQUOTE: char = '"';
const CHAR_LBRC: char = '[';
const CHAR_RBRC: char = ']';
const CHAR_LCBR: char = '{';
const CHAR_RCBR: char = '}';
const CHAR_COLON: char = ':';
const CHAR_SEMICOLON: char = ';';
const CHAR_DOT: char = '.';
const CHAR_EXCLAIM: char = '!';
const CHAR_DASH: char = '-';
const CHAR_TILDE: char = '~';
const CHAR_EQUAL: char = '=';
const CHAR_SLASH: char = '/';
const CHAR_BSLSH: char = '\\';
const CHAR_LPRN: char = '(';
const CHAR_RPRN: char = ')';
const CHAR_N0: char = '0';
const CHAR_N1: char = '1';
const CHAR_N2: char = '2';
const CHAR_N3: char = '3';
const CHAR_N4: char = '4';
const CHAR_N5: char = '5';
const CHAR_N6: char = '6';
const CHAR_N7: char = '7';
const CHAR_N8: char = '8';
const CHAR_N9: char = '9';

pub fn lex_line() {}
